// Code generated by go-swagger; DO NOT EDIT.

package v1imagecatalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetImagesByClusterNameAndCustomImageCatalogParams creates a new GetImagesByClusterNameAndCustomImageCatalogParams object
// with the default values initialized.
func NewGetImagesByClusterNameAndCustomImageCatalogParams() *GetImagesByClusterNameAndCustomImageCatalogParams {
	var ()
	return &GetImagesByClusterNameAndCustomImageCatalogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetImagesByClusterNameAndCustomImageCatalogParamsWithTimeout creates a new GetImagesByClusterNameAndCustomImageCatalogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetImagesByClusterNameAndCustomImageCatalogParamsWithTimeout(timeout time.Duration) *GetImagesByClusterNameAndCustomImageCatalogParams {
	var ()
	return &GetImagesByClusterNameAndCustomImageCatalogParams{

		timeout: timeout,
	}
}

// NewGetImagesByClusterNameAndCustomImageCatalogParamsWithContext creates a new GetImagesByClusterNameAndCustomImageCatalogParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetImagesByClusterNameAndCustomImageCatalogParamsWithContext(ctx context.Context) *GetImagesByClusterNameAndCustomImageCatalogParams {
	var ()
	return &GetImagesByClusterNameAndCustomImageCatalogParams{

		Context: ctx,
	}
}

// NewGetImagesByClusterNameAndCustomImageCatalogParamsWithHTTPClient creates a new GetImagesByClusterNameAndCustomImageCatalogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetImagesByClusterNameAndCustomImageCatalogParamsWithHTTPClient(client *http.Client) *GetImagesByClusterNameAndCustomImageCatalogParams {
	var ()
	return &GetImagesByClusterNameAndCustomImageCatalogParams{
		HTTPClient: client,
	}
}

/*GetImagesByClusterNameAndCustomImageCatalogParams contains all the parameters to send to the API endpoint
for the get images by cluster name and custom image catalog operation typically these are written to a http.Request
*/
type GetImagesByClusterNameAndCustomImageCatalogParams struct {

	/*ClusterName*/
	ClusterName string
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get images by cluster name and custom image catalog params
func (o *GetImagesByClusterNameAndCustomImageCatalogParams) WithTimeout(timeout time.Duration) *GetImagesByClusterNameAndCustomImageCatalogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get images by cluster name and custom image catalog params
func (o *GetImagesByClusterNameAndCustomImageCatalogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get images by cluster name and custom image catalog params
func (o *GetImagesByClusterNameAndCustomImageCatalogParams) WithContext(ctx context.Context) *GetImagesByClusterNameAndCustomImageCatalogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get images by cluster name and custom image catalog params
func (o *GetImagesByClusterNameAndCustomImageCatalogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get images by cluster name and custom image catalog params
func (o *GetImagesByClusterNameAndCustomImageCatalogParams) WithHTTPClient(client *http.Client) *GetImagesByClusterNameAndCustomImageCatalogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get images by cluster name and custom image catalog params
func (o *GetImagesByClusterNameAndCustomImageCatalogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterName adds the clusterName to the get images by cluster name and custom image catalog params
func (o *GetImagesByClusterNameAndCustomImageCatalogParams) WithClusterName(clusterName string) *GetImagesByClusterNameAndCustomImageCatalogParams {
	o.SetClusterName(clusterName)
	return o
}

// SetClusterName adds the clusterName to the get images by cluster name and custom image catalog params
func (o *GetImagesByClusterNameAndCustomImageCatalogParams) SetClusterName(clusterName string) {
	o.ClusterName = clusterName
}

// WithName adds the name to the get images by cluster name and custom image catalog params
func (o *GetImagesByClusterNameAndCustomImageCatalogParams) WithName(name string) *GetImagesByClusterNameAndCustomImageCatalogParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get images by cluster name and custom image catalog params
func (o *GetImagesByClusterNameAndCustomImageCatalogParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetImagesByClusterNameAndCustomImageCatalogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param clusterName
	if err := r.SetPathParam("clusterName", o.ClusterName); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
