// Code generated by go-swagger; DO NOT EDIT.

package v1imagecatalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/models_cloudbreak"
)

// GetImagesByClusterNameAndCustomImageCatalogReader is a Reader for the GetImagesByClusterNameAndCustomImageCatalog structure.
type GetImagesByClusterNameAndCustomImageCatalogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImagesByClusterNameAndCustomImageCatalogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetImagesByClusterNameAndCustomImageCatalogOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetImagesByClusterNameAndCustomImageCatalogOK creates a GetImagesByClusterNameAndCustomImageCatalogOK with default headers values
func NewGetImagesByClusterNameAndCustomImageCatalogOK() *GetImagesByClusterNameAndCustomImageCatalogOK {
	return &GetImagesByClusterNameAndCustomImageCatalogOK{}
}

/*GetImagesByClusterNameAndCustomImageCatalogOK handles this case with default header values.

successful operation
*/
type GetImagesByClusterNameAndCustomImageCatalogOK struct {
	Payload *models_cloudbreak.ImagesResponse
}

func (o *GetImagesByClusterNameAndCustomImageCatalogOK) Error() string {
	return fmt.Sprintf("[GET /v1/imagecatalogs/account/valid/{name}/{clusterName}][%d] getImagesByClusterNameAndCustomImageCatalogOK  %+v", 200, o.Payload)
}

func (o *GetImagesByClusterNameAndCustomImageCatalogOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_cloudbreak.ImagesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
