// Code generated by go-swagger; DO NOT EDIT.

package v1organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeletePrivateOrganizationReader is a Reader for the DeletePrivateOrganization structure.
type DeletePrivateOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePrivateOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeletePrivateOrganizationDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeletePrivateOrganizationDefault creates a DeletePrivateOrganizationDefault with default headers values
func NewDeletePrivateOrganizationDefault(code int) *DeletePrivateOrganizationDefault {
	return &DeletePrivateOrganizationDefault{
		_statusCode: code,
	}
}

/*DeletePrivateOrganizationDefault handles this case with default header values.

successful operation
*/
type DeletePrivateOrganizationDefault struct {
	_statusCode int
}

// Code gets the status code for the delete private organization default response
func (o *DeletePrivateOrganizationDefault) Code() int {
	return o._statusCode
}

func (o *DeletePrivateOrganizationDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/organizations/t/{name}][%d] deletePrivateOrganization default ", o._statusCode)
}

func (o *DeletePrivateOrganizationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
