// Code generated by go-swagger; DO NOT EDIT.

package v1organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePrivateOrganizationParams creates a new DeletePrivateOrganizationParams object
// with the default values initialized.
func NewDeletePrivateOrganizationParams() *DeletePrivateOrganizationParams {
	var ()
	return &DeletePrivateOrganizationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePrivateOrganizationParamsWithTimeout creates a new DeletePrivateOrganizationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePrivateOrganizationParamsWithTimeout(timeout time.Duration) *DeletePrivateOrganizationParams {
	var ()
	return &DeletePrivateOrganizationParams{

		timeout: timeout,
	}
}

// NewDeletePrivateOrganizationParamsWithContext creates a new DeletePrivateOrganizationParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePrivateOrganizationParamsWithContext(ctx context.Context) *DeletePrivateOrganizationParams {
	var ()
	return &DeletePrivateOrganizationParams{

		Context: ctx,
	}
}

// NewDeletePrivateOrganizationParamsWithHTTPClient creates a new DeletePrivateOrganizationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePrivateOrganizationParamsWithHTTPClient(client *http.Client) *DeletePrivateOrganizationParams {
	var ()
	return &DeletePrivateOrganizationParams{
		HTTPClient: client,
	}
}

/*DeletePrivateOrganizationParams contains all the parameters to send to the API endpoint
for the delete private organization operation typically these are written to a http.Request
*/
type DeletePrivateOrganizationParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete private organization params
func (o *DeletePrivateOrganizationParams) WithTimeout(timeout time.Duration) *DeletePrivateOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete private organization params
func (o *DeletePrivateOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete private organization params
func (o *DeletePrivateOrganizationParams) WithContext(ctx context.Context) *DeletePrivateOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete private organization params
func (o *DeletePrivateOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete private organization params
func (o *DeletePrivateOrganizationParams) WithHTTPClient(client *http.Client) *DeletePrivateOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete private organization params
func (o *DeletePrivateOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete private organization params
func (o *DeletePrivateOrganizationParams) WithName(name string) *DeletePrivateOrganizationParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete private organization params
func (o *DeletePrivateOrganizationParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePrivateOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
