// Code generated by go-swagger; DO NOT EDIT.

package v1organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/models_cloudbreak"
)

// NewPostOrganizationParams creates a new PostOrganizationParams object
// with the default values initialized.
func NewPostOrganizationParams() *PostOrganizationParams {
	var ()
	return &PostOrganizationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostOrganizationParamsWithTimeout creates a new PostOrganizationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostOrganizationParamsWithTimeout(timeout time.Duration) *PostOrganizationParams {
	var ()
	return &PostOrganizationParams{

		timeout: timeout,
	}
}

// NewPostOrganizationParamsWithContext creates a new PostOrganizationParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostOrganizationParamsWithContext(ctx context.Context) *PostOrganizationParams {
	var ()
	return &PostOrganizationParams{

		Context: ctx,
	}
}

// NewPostOrganizationParamsWithHTTPClient creates a new PostOrganizationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostOrganizationParamsWithHTTPClient(client *http.Client) *PostOrganizationParams {
	var ()
	return &PostOrganizationParams{
		HTTPClient: client,
	}
}

/*PostOrganizationParams contains all the parameters to send to the API endpoint
for the post organization operation typically these are written to a http.Request
*/
type PostOrganizationParams struct {

	/*Body*/
	Body *models_cloudbreak.OrganizationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post organization params
func (o *PostOrganizationParams) WithTimeout(timeout time.Duration) *PostOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post organization params
func (o *PostOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post organization params
func (o *PostOrganizationParams) WithContext(ctx context.Context) *PostOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post organization params
func (o *PostOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post organization params
func (o *PostOrganizationParams) WithHTTPClient(client *http.Client) *PostOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post organization params
func (o *PostOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post organization params
func (o *PostOrganizationParams) WithBody(body *models_cloudbreak.OrganizationRequest) *PostOrganizationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post organization params
func (o *PostOrganizationParams) SetBody(body *models_cloudbreak.OrganizationRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(models_cloudbreak.OrganizationRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
