// Code generated by go-swagger; DO NOT EDIT.

package v3_organization_id_stack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/models_cloudbreak"
)

// DeleteStackInOrganizationReader is a Reader for the DeleteStackInOrganization structure.
type DeleteStackInOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteStackInOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteStackInOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteStackInOrganizationOK creates a DeleteStackInOrganizationOK with default headers values
func NewDeleteStackInOrganizationOK() *DeleteStackInOrganizationOK {
	return &DeleteStackInOrganizationOK{}
}

/*DeleteStackInOrganizationOK handles this case with default header values.

successful operation
*/
type DeleteStackInOrganizationOK struct {
	Payload *models_cloudbreak.StackResponse
}

func (o *DeleteStackInOrganizationOK) Error() string {
	return fmt.Sprintf("[DELETE /v3/{organizationId}/stack/{name}][%d] deleteStackInOrganizationOK  %+v", 200, o.Payload)
}

func (o *DeleteStackInOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_cloudbreak.StackResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
