// Code generated by go-swagger; DO NOT EDIT.

package v3_organization_id_stack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/models_cloudbreak"
)

// PutscalingStackV3Reader is a Reader for the PutscalingStackV3 structure.
type PutscalingStackV3Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutscalingStackV3Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutscalingStackV3OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutscalingStackV3OK creates a PutscalingStackV3OK with default headers values
func NewPutscalingStackV3OK() *PutscalingStackV3OK {
	return &PutscalingStackV3OK{}
}

/*PutscalingStackV3OK handles this case with default header values.

successful operation
*/
type PutscalingStackV3OK struct {
	Payload *models_cloudbreak.StackResponse
}

func (o *PutscalingStackV3OK) Error() string {
	return fmt.Sprintf("[PUT /v3/{organizationId}/stack/{name}/scaling][%d] putscalingStackV3OK  %+v", 200, o.Payload)
}

func (o *PutscalingStackV3OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_cloudbreak.StackResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
